server:
  port: 8020

  #应用名称（nacos会将该名称当做服务名称）
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public